export const MENU = {
	LOGIN: '/webcms/',
	PLANNING : '/webcms/planning',
	PLANNING_INPUT_LIFETIME : '/webcms/planning/input-lifetime',
	PLANNING_SITE : '/webcms/planning/site',
	PLANNING_HO_STATUS: '/webcms/planning/ho/status',
	PLANNING_SITE_STATUS: '/webcms/planning/site/status',
	PLANNING_HO: '/webcms/planning/ho',
	PLANNING_TRACKING_HISTORY:'/webcms/planning/tracking-history',
	PLANNING_DASHBOARD : '/webcms/planning/dashboard',
	PLANNING_ALL_NOTIF : '/webcms/planning/all-notification',
	PLANNING_HO_SAP: '/webcmsjs/planning/ho/sap-issue',
	DASHBOARD: '/webcms/dashboard',
	ALLOCATION: '/webcmsjs/allocation',
	SETTINGS: '/websmsjs/settings',
	LOGOUT: '/websmsjs/logout',
};