apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web-cms-js
  labels:
    app: web-cms-js
    workstream: cms
    version: 1.0.0
    tier: frontend
    usermanagementservice: "true"
    msplanning: "true"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web-cms-js
        workstream: cms
        version: 1.0.0
        tier: frontend
        usermanagementservice: "true"
        msplanning: "true"
    spec:
      containers:
      - name: web-cms-js
        image: myicp.unitedtractors.com:8500/cms/web-cms-js:#{Build.BuildId}#
        ports:
        - containerPort: 8080
          name: http
---
kind: Service
apiVersion: v1
metadata:
  name: web-cms-js
  labels:
    app: web-cms-js
    workstream: cms
    version: 1.0.0
    tier: frontend
    usermanagementservice: "true"
    msplanning: "true"
spec:
   ports:
   - port: 8080
   selector:
     app: web-cms-js
   type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: web-cms-js
spec:
  rules:
  - host: web-cms-js.proxyicp.unitedtractors.com
    http:
      paths:
      - backend:
          serviceName: web-cms-js
          servicePort: 8080